name: tenka_dev_tools
description: "👷 Developer tools of Tenka."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    colorize: ^3.0.0
    baize_compiler:
        git:
            url: https://github.com/zyrouge/baize.git
            path: packages/baize_compiler
    path: ^1.8.3
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx
    yaml: ^3.1.2

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
