name: devx
description: "🚨 Contains developer guideline preferences of Dart projects related to Yukino Org."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies: 
    flutter_lints: ^2.0.1
   