name: utilx
description: "🔧 Contains utility tools used in Dart projects related to Yukino."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    meta: ^1.7.0

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
