name: tenka_dev_tools
description: "👷 Developer tools of Tenka."
version: 0.0.0

publish_to: none

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    beize_compiler:
        git:
            url: https://github.com/zyrouge/beize.git
            path: packages/beize_compiler
    colorize: ^3.0.0
    path: ^1.8.3
    tenka:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_utilx
    yaml: ^3.1.2

dev_dependencies:
    devx:
        git:
            url: https://github.com/yukino-org/packages.git
            ref: dart_devx
